language: haskell
matrix:
  fast_finish: true
  include:
    - ghc: 7.8
    - ghc: 7.6
    - ghc: 7.3
  allow_failures:
    - ghc: 7.8
      install: cabal install --only-dependencies --enable-tests -f NoUpperBounds
